grafana:
  adminPassword: coe@2024
  ingress:
    enabled: true
    hosts:
      - grafana.srmvcas.org
    tls:
      - hosts:
          - grafana.srmvcas.org
        secretName: grafana-tls
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
  sidecar:
    datasources:
      env:
        SKIP_TLS_VERIFY: "true"
    dashboards:
      annotations:
        grafana_folder: "kubernetes"
      defaultFolderName: "General"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true
      env:
        SKIP_TLS_VERIFY: "true"